name: 'Version Pom.xml'
description: 'Set Version in pom.xml'
inputs:
  version:
    description: 'Version'
    required: true
  tag:
    description: 'Tag'
    required: true

runs:
  using: "composite"
  steps:
  - name: Set version to SNAPSHOT
    run: mvn versions:set -DnewVersion=${{ inputs.tag }}-${{ inputs.ambiente }}
    shell: bash