name: CI Workflow
on:
  workflow_dispatch:
    branches:
      - feature/devops
      - main
 
env:
  AMBIENTE: ${{ (github.ref == 'refs/heads/main' && 'dev') }} # || (github.ref == 'refs/heads/qa' && 'qa') }} || (github.ref == 'refs/heads/qa' && 'pro') }}
  VERSION: ${{ (github.ref == 'refs/heads/main' && 'SNAPSHOT') }}

jobs:

  setup-vm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: [ '3.9.6' ]
        java: ['17']
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: setup-vm

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        id: vars
        uses: ./.github/workflows/set-up-env
        with:
          ambiente: ${{ env.AMBIENTE }}

      
      - name: Set tag
        id: tag
        uses: ./.github/workflows/acr-tag

      - name: Use environment variables
        run: |
          echo "AMBIENTE: ${{ env.AMBIENTE }}"
          echo "NAMESPACE: ${{ env.namespace }}"
          echo "CLUSTER_NAME: ${{ env.cluster_name }}"
          echo "CLUSTER_RESOURCE_GROUP: ${{ env.cluster_resource_group }}"
          echo "TAG: ${{ env.tag }}"
        shell: bash

      - name: Set version in pom.xml
        id: vars
        uses: ./.github/workflows/version
        with:
          version: ${{ env.VERSION }}
          tag: ${{ env.tag }}
      
      - name: leer pom.xml
        run: cat pom.xml
