name: CI Workflow
on:
  workflow_dispatch:
    branches:
      - feature/devops
      - main
 
env:
  AMBIENTE: ${{ (github.ref == 'refs/heads/main' && 'dev') }} # || (github.ref == 'refs/heads/qa' && 'qa') }} || (github.ref == 'refs/heads/qa' && 'pro') }}
  # NAMESPACE: microservice-${{ env.AMBIENTE }}
  # CLUSTER_NAME: AZ-EASTUS-BSP-${{ env.AMBIENTE }}-NEWOBW-AKS2
  # CLUSTER_RESOURCE_GROUP: AZ-EASTUS-BSP-${{ env.AMBIENTE }}-NEWOBW-ALL-RG

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      NAMESPACE: microservice-${{ env.NAMESPACE }}
      CLUSTER_NAME: AZ-EASTUS-BSP-${{ env.CLUSTER_NAME }}-NEWOBW-AKS2
      CLUSTER_RESOURCE_GROUP: AZ-EASTUS-BSP-${{ env.CLUSTER_RESOURCE_GROUP }}-NEWOBW-ALL-RG
    steps:
      - run: |
          echo "AMBIENTE: ${{ env.AMBIENTE }}"
          echo "NAMESPACE: ${{ env.NAMESPACE }}"
          echo "CLUSTER_NAME: ${{ env.CLUSTER_NAME }}"}
          echo "CLUSTER_RESOURCE_GROUP: ${{ env.CLUSTER_RESOURCE_GROUP }}"